before_install:
  - sudo aptitude -y -q install curl make libgc-dev libasound2-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin
  - git clone --depth=1 git://github.com/kinetiknz/cubeb.git
  - mkdir prefix
  - export PREFIX=$PWD/prefix
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PREFIX/lib/pkgconfig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib
  - cd cubeb
  - autoreconf --install
  - ./configure --prefix=$PREFIX
  - make && make install
  - cd ..

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v tone.ooc -o=travis/tone

